#!/bin/bash
source /usr/lib/elive-tools/functions


echo "$(date -s)|$(pwd)|$(basename $0)|user:${USER}|display:${DISPLAY}" >> /tmp/logs.txt

zenity --info --text="$(date -s)|$(pwd)|$(basename $0)|user:${USER}|display:${DISPLAY}"


